/* ============================================================
   PAGE: Trending Topics Word Cloud
   ============================================================ */

Pages = window.Pages || {};

Pages.trending = function (root) {
  const prefs = Store.getPrefs();
  const weekPool = Agent.pollSources(prefs.domains); // stand-in for "this week's" articles
  const terms = Agent.getTrendingTerms(weekPool);

  root.innerHTML = `
    <div class="shell">
      <div class="eyebrow" style="margin-top:36px;">Trending</div>
      <h1 class="page-title">This week in ${prefs.domains.map((d) => DOMAIN_META[d].label.toLowerCase()).join(", ")}</h1>
      <p class="page-sub">Generated by the agent from every tag across this week's digest. Bigger and brighter means it came up more often.</p>

      <div class="cloud-wrap" id="cloud"></div>

      <div class="legend-row">
        ${Object.entries(DOMAIN_META)
          .map(([k, m]) => `<span class="item"><span class="swatch" style="background:${m.accent}"></span>${m.label}</span>`)
          .join("")}
      </div>

      <table class="trend-table">
        <thead><tr><th>Term</th><th>Domain</th><th>Mentions</th><th></th></tr></thead>
        <tbody id="trend-rows"></tbody>
      </table>
    </div>
  `;

  const cloudEl = root.querySelector("#cloud");
  const rowsEl = root.querySelector("#trend-rows");

  if (terms.length === 0) {
    cloudEl.innerHTML = `<div class="empty-state">No tags to show yet. Activate a domain in preferences.</div>`;
    return;
  }

  const max = terms[0].count;
  const min = terms[terms.length - 1].count;
  const scale = (count) => {
    if (max === min) return 22;
    return 14 + ((count - min) / (max - min)) * 34; // 14px..48px
  };

  cloudEl.innerHTML = terms
    .map((t) => {
      const size = scale(t.count).toFixed(0);
      const color = DOMAIN_META[t.domain].accent;
      return `<span class="cloud-term" style="font-size:${size}px; color:${color};" title="${t.count} mention${t.count > 1 ? "s" : ""}">${t.term}</span>`;
    })
    .join("");

  rowsEl.innerHTML = terms
    .map((t) => {
      const meta = DOMAIN_META[t.domain];
      const pct = Math.round((t.count / max) * 100);
      return `
        <tr>
          <td>${t.term}</td>
          <td><span class="domain-pill ${t.domain}">${meta.glyph} ${meta.label}</span></td>
          <td>${t.count}</td>
          <td><div class="trend-bar"><span style="width:${pct}%; background:${meta.accent};"></span></div></td>
        </tr>
      `;
    })
    .join("");
};
