import {
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ReferenceDot,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis
} from "recharts";
import { useState } from "react";

export default function ExchangeRateChart({ series, annotations }) {
  const annotationMap = new Map(annotations.map((item) => [item.date, item]));
  const [hoveredEvent, setHoveredEvent] = useState(null);

  return (
    <section className="panel chart-panel">
      <h2>Exchange Rate Chart</h2>
      <p className="subtext">Nominal vs inflation-adjusted line generated by the analysis agent.</p>

      <div className="chart-wrap">
        <ResponsiveContainer width="100%" height={340}>
          <LineChart data={series} margin={{ top: 20, right: 16, bottom: 10, left: 4 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="rgba(0,0,0,0.12)" />
            <XAxis dataKey="date" minTickGap={36} tick={{ fontSize: 12 }} />
            <YAxis tick={{ fontSize: 12 }} />
            <Tooltip
              formatter={(value, name) => [Number(value).toFixed(4), name]}
              labelFormatter={(date) => {
                const event = annotationMap.get(date);
                return event ? `${date} | ${event.title}` : date;
              }}
              contentStyle={{ borderRadius: 12, border: "1px solid #1f1f1f" }}
            />
            <Legend />
            <Line
              type="monotone"
              dataKey="nominalRate"
              name="Nominal"
              stroke="#0f4c5c"
              strokeWidth={2.4}
              dot={false}
            />
            <Line
              type="monotone"
              dataKey="realRate"
              name="Inflation-adjusted"
              stroke="#d1495b"
              strokeWidth={2.4}
              dot={false}
            />
            {annotations.map((event) => {
              const point = series.find((s) => s.date === event.date);
              if (!point) return null;
              return (
                <ReferenceDot
                  key={`${event.date}-${event.title}`}
                  x={event.date}
                  y={point.nominalRate}
                  r={4}
                  fill="#edae49"
                  stroke="#1f1f1f"
                  onMouseEnter={() => setHoveredEvent(event)}
                  onMouseLeave={() => setHoveredEvent(null)}
                />
              );
            })}
          </LineChart>
        </ResponsiveContainer>
      </div>

      <div className="hover-note">
        {hoveredEvent ? (
          <p>
            <strong>{hoveredEvent.title}</strong> ({hoveredEvent.date}): {hoveredEvent.explanation}
          </p>
        ) : (
          <p>Hover a gold event marker on the chart to read the agent explanation.</p>
        )}
      </div>
    </section>
  );
}
